[project]
name = "raja"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dr. Ernie Prabhakar", email = "ernest@quilt.bio" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"
